### PR TITLE
Fix BoundingBox center size constructor

### PR DESCRIPTION
**Pull request by fabioarnold**

### CODE REVIEW

**Comment by fabioarnold** [comment]
Tried to fix the inserted newline at the end of the file in https://github.com/ExOK/Celeste64/pull/89/commits/4ba16b6bf9fa3043d5d42b5e0992ad822767f6b0 but GitHub won't let me. 🤷

**Comment by NoelFB** [comment]
Oh whoa, yeah i think when I coded this I must have thought it was Min/Size, not Min/Max. This seems good to fix as long as it doesn't break anything in the game (since now some stuff, I assume, will have a smaller bounding box?)

**Comment by fabioarnold** [comment]
Right, the bounding boxes will be smaller. To be honest I haven't tested the game with this change. I just stumbled upon this line while I was porting this game to Zig/WASM (https://fabioarnold.de/games/celeste64). In the beginning I just wanted to port part of the tech (Quake maps/glTF loader/physics) for my own game. But now it turned into actually completing the porting, haha. 😅
Amazing work, btw! I can't believe you guys pulled this off in a span of a game jam.

**Comment by NoelFB** [comment]
This looks like a really cool project, I'm very curious to see what the end result and source code look like (I've always wanted to mess around in Zig but haven't had a chance!)

**Comment by fabioarnold** [comment]
Thanks! :) The code is over here: https://github.com/fabioarnold/3d-game Currently, I don't have time to work on it since I'm finishing something else right now. But I could ping you once it's done.
On the technical side, I had to come up with a manual solution for multi-level inheritance for the actors. And I used vtables (same as Zig allocators). I haven't found a good general solution for co-routines yet. So, I translated them to state machines. Really shows how ergonomic C# is for gamedev. Or at least if you architect the code in this way. What I like about Zig, other than the simple language itself, is the quick compile times and probably the build system. Here's hot code reloading: https://twitter.com/captainhorst/status/1754301597859852289 (which I broke once I started to more literally port the actual game).

**Pull request merged**
