### PR TITLE
CI: build for arm64 and arm32 Linux and arm64 macOS

### PR DESCRIPTION
**Pull request by theofficialgman**
closes https://github.com/ExOK/Celeste64/issues/23

I am hoping this gets published on itch.io!

See https://github.com/theofficialgman/Celeste64/releases/tag/v1.1.0-arm64 for test build

### CODE REVIEW

**Comment by NoelFB** [comment]
Looks great, thank you! Yeah I would like to publish these on itch in the near future.

**Comment by theofficialgman** [comment]
Ready to merge once https://github.com/FosterFramework/Foster/pull/62 is merged and the dependency here is bumped

**Comment by NoelFB** [comment]
Foster is updated, waiting for NuGet to index 0.1.18

**Comment by NoelFB** [comment]
Looks like it's up now.

**Comment by theofficialgman** [comment]
I am going to switch macOS to an osx-any build (arm64 and x64 in one executable).
Are you able to test that on an x64 or arm64 (preferably both) mac?

**Comment by NoelFB** [comment]
I unfortunately don't have access to a mac at all right now :(

**Comment by NoelFB** [comment]
Is this good to merge in? I see it's not in draft state anymore but not sure if there's anything else you wanted to tweak!

**Comment by theofficialgman** [comment]
> I am going to switch macOS to an osx-any build (arm64 and x64 in one executable). Are you able to test that on an x64 or arm64 (preferably both) mac?

sorry I was mistake about this. it appears to not be supported automatically as of now https://github.com/dotnet/sdk/issues/9795
since I am not a macos developer and can't even test that I will leave it separate for now

**Comment by theofficialgman** [comment]
tested. all good on ARM32 linux and ARM64 linux

**Comment by NoelFB** [comment]
Awesome, thanks for your work on this!

**Pull request merged**
