### PR TITLE
Add submenus and menu titles

### LINKED ISSUE #41: Make Options a Submenu
I think game options should be in a submenu as there are going to be too many in not-too-long, similar to how 2D Celeste does it.

### PR DESCRIPTION
**Pull request by JoshuaMadd**
fix #41 

I added submenu support and put the options in a submenu. I also added titles so you know what menu you're in.
It is also possible to add submenus in submenus which doesn't have a purpose yet, but could be usefull in the future (e.g. to add keybind options in the options submenu). 

There are some minor alignement issues I didn't know how to fix and I also didn't find how to make the title bigger.

I'm new to all this stuff, so any feedback would be greatly appreciated:)

### CODE REVIEW

**Comment by NoelFB** [comment]
Hey thanks for tackling this, this looks like a great start! I think my only immediate request is that the function calls be capitalized camel-case, to keep in style with standard C# (so ex. `isInMainMenu` -> `IsInMainMenu`)

**Comment by NoelFB** [comment]
I'm actually gonna merge this in and tweak the naming! Thanks for setting this up! :)

**Comment by Gamingjojo909** [comment]
Sure:) Had a lot of work today so I didn't have time to fix it myself:p

**Comment by NoelFB** [comment]
All good, I appreciate the work to get it setup! :)

**Pull request merged**
