### PR TITLE
Add the option to invert the camera

### PR DESCRIPTION
**Pull request by hacktic-dev**
Adding in an inverted camera option. The UI can be reorganised or changed if needed. 
invert

### CODE REVIEW

**Comment by NoelFB** [comment]
I think this is a good idea but I want to add it to the submenu in #46 before we merge this in.
The other thing that would be nice is if this was somehow a single menu option instead of two... But I'm not sure how. Maybe an enum (None, X, Y, Both) and make a new Slider Menu option for it. (like `SliderEnum` or something).

**Comment by hacktic-dev** [comment]
Yep we can do that! I do agree its a good idea to merge #46 in first. Once we have that I can update this PR and move it into the submenu

**Comment by NoelFB** [comment]
Alright #46 is merged in. If you're open to tackling adding a SliderEnum menu subclass I'm down to support this!

**Comment by hacktic-dev** [comment]
Okay awesome. I'll take a look into this tomorrow

**Comment by hacktic-dev** [comment]
I'll close this PR and make a new one accounting for the localisation changes etc.

**Pull request closed without merging**
