### PR TITLE
Github Actions build pipeline for all platforms

### PR DESCRIPTION
**Pull request by amandamxavier**
Hi there! 👋

I've created a pipeline for building the macOS version and decided to expand it to support all platforms.

It builds and generates a GitHub Release with a brief instruction and attaches the .zip files for Windows, Linux and macOS both in x64 and arm64 architectures.

Oh, it's triggered by pushing tags to the repository.

Let me know if it can be useful or if it needs something more.

### CODE REVIEW

**Comment by NoelFB** [comment]
This looks great, thank you! Just to double-check, does this work around https://github.com/ExOK/Celeste64/issues/19? I know locally when I `dotnet publish` it will copy the fmod DLLs of my local os/architecture, not the target one. If that is working fine then I'll merge this in!

**Comment by NoelFB** [comment]
Alright #19 is fixed now. My only remaining question is whether it should run on tags, or on publishing releases... I'm not super familiar with github tags/releases so not entirely sure what is best. Is there a reason to use tags over releases?
for example:
```yaml
on:
  release:
    types: [published]
```

**Comment by computermouth** [comment]
Probably the biggest distinction would be that you can push tags with any ole git client. I think you have to use the github client to create a release.

**Comment by amandamxavier** [comment]
@computermouth is correct.

Releases is a feature of GitHub for publishing versions of projects based on new tags, pushes, or merges, and including some notes of the changes, maybe new instructions on how to use it, etc.

There's an example of the release generated by this pipeline on my repository [here](https://github.com/amandamxavier/celeste-64/releases/tag/v1.01).

You can create and push tags with Git, but with GitHub, you can only create tags by first creating a release. I don't know why exactly they did this, or if it's just a missed feature for now.

Anyways, about the trigger, we can change it to however is best suitable for the project, e.g. tags, pushes, merges, etc.

The way I did, it will:

- Start the GitHub Action when a `git push --tags` with a new tag is pushed.
- Create automatically a release here on GitHub with a boilerplate description, and a title, e.g. Release v1.01 (if the tag pushed is v1.01).
- Build and compress to a zip file for every platform.
- Attach it to the Release created and publish it.

We can also change it to just make a draft release, so we can maybe manually edit and add a release note for example.

**Comment by amandamxavier** [comment]
I've noticed some issues and I'm fixing them now, so will commit soon and include it here.

- [ ] Content folder is not being copied to the publish files*
- [ ] While the Action runs on Ubuntu, it is using Linux FMod files for every platform**

*I don't know if I'm doing something wrong but the `dotnet publish` just doesn't copy it, so I'll copy it manually.
**I've seen that @NoelFB has already fixed it, but I'll change the pipeline to run simultaneously on 3 machines for the 3 platforms, so it will also improve the GitHub Actions time, and shorten the workflow file.

**Comment by NoelFB** [comment]
I think both those solutions make sense (copy Content file and also run concurrent on each OS)! Thanks for solving this! :)

**Comment by amandamxavier** [comment]
- [x] Content folder correctly copied before compressing to zip
- [x] Building on three platforms simultaneously, reducing build time from ≈1m:50s to ≈1m:10s

If it interests you is also possible to automate the uploading to itch.io with [this action](https://github.com/marketplace/actions/itch-io-upload) and the signing and notarization of the macOS version (you can [check here](https://github.com/martincostello/dotnet-macos-notarization-example/blob/main/.github/workflows/build.yml) a GitHub Actions example pipeline).

I will be here if you find something in need to still work on this PR 😊

**Comment by NoelFB** [comment]
This looks good to me, thank you! Merging in!

**Pull request merged**
